extends:
  - "spectral:oas"
  - "@stoplight/spectral-owasp-ruleset"

rules:
  operation-id-required:
    description: "Every OpenAPI operation must have an operationId specified."
    message: "Operation object is missing operationId."
    severity: error
    given: "$.paths[*][*]"
    then:
      field: operationId
      function: truthy
  x-internal-server-required:
    description: "Every OpenAPI must have an x-internal-server specified."
    message: "x-internal-server object is missing."
    severity: error
    given: "$"
    then:
      field: x-internal-server
      function: truthy
  x-internal-server-url-required:
    description: "x-internal-server must have a url."
    message: "x-internal-server object is missing url."
    severity: error
    given: "$"
    then:
      field: x-internal-server.url
      function: truthy
  x-internal-server-description-required:
    description: "x-internal-server must have a description."
    message: "x-internal-server object is missing description."
    severity: error
    given: "$"
    then:
      field: x-internal-server.description
      function: truthy

  # OWASP API Security
  # Overwrite default severity to warn just for demo purposes
  owasp:api2:2023-write-restricted: warn
  owasp:api4:2023-rate-limit: warn
  owasp:api4:2023-integer-limit-legacy: warn
  owasp:api4:2023-string-limit: warn
  owasp:api8:2023-no-server-http: warn
  owasp:api4:2023-integer-limit: warn
  owasp:api1:2023-no-numeric-ids: warn
  owasp:api4:2023-integer-format: warn
  owasp:api4:2023-array-limit: warn
  owasp:api2:2023-jwt-best-practices: warn
