---
apiVersion: v1
kind: Namespace
metadata:
  name: kong-edu

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankong-frontend
  namespace: kong-edu
  labels:
    app: bankong-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankong-frontend
  template:
    metadata:
      labels:
        app: bankong-frontend
    spec:
      containers:
        - name: bankong-frontend
          image: svenwal/bankong-frontend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bankong-frontend
  namespace: kong-edu
spec:
  selector:
    app: bankong-frontend
  ports:
    - protocol: TCP
      port: 80        # Kubernetes Service port
      targetPort: 8080 # Container's exposed port
  type: NodePort      # You can also use LoadBalancer for external access

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankong-backend-transactions
  namespace: kong-edu
  labels:
    app: bankong-backend-transactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankong-backend-transactions
  template:
    metadata:
      labels:
        app: bankong-backend-transactions
    spec:
      containers:
        - name: bankong-backend-transactions
          image: svenwal/bankong-backend-transactions:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_REGION
              value: "your home"
            - name: BACKEND_DATACENTER
              value: "local laptop"
            - name: BACKEND_ARCHITECTURE
              value: "docker-compose"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bankong-backend-transactions
  namespace: kong-edu
spec:
  selector:
    app: bankong-backend-transactions
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: ClusterIP
