image:
  repository: kong/kong-gateway
  tag: "3.7.0.0"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
ingressController:
  enabled: false
  installCRDs: false