datadog:
  processAgent:
    enabled: true
  orchestratorExplorer:
    enabled: true
  otlp:
    logs:
      enabled: true
    receiver:
      protocols:
        http:
          enabled: true
  kubelet:
    tlsVerify: false
  apm:
    socketEnabled: true
  env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DD_ENV
      value: demo
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.eu
  tags:
    - env:demo
  logs:
    enabled: true
    containerCollectAll: true
