apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector-kong-collector
  labels:
    app: collector-kong-collector
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
      - 'namespaces'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
  - apiGroups:
      - 'apps'
    resources:
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'extensions'
    resources:
      - 'replicasets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector-kong-collector
  labels:
    app: collector-kong-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector-kong-collector
subjects:
  - kind: ServiceAccount
    name: collector-kong-collector
    namespace: opentelemetry-operator-system