mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.116.1
extraEnvs:
- name: DT_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_TOKEN
- name: DT_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_ENDPOINT
resources:
  limits:
    memory: 512Mi
alternateConfig:
  extensions:
    health_check:
     endpoint: "${env:MY_POD_IP}:13133"
  
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            scheme: http
            metrics_path: /metrics
            kubernetes_sd_configs:
              - role: pod
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            authorization:
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              action: keep
              regex: "kong"
            - source_labels: [__meta_kubernetes_pod_name]
              action: keep
              regex: "kong-kong-(.+)"
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: keep
              regex: "proxy"
            - source_labels: [__meta_kubernetes_pod_container_port_number]
              action: keep
              regex: "8100"
    filelog: null

  processors:
    cumulativetodelta:

  exporters:
    otlphttp:
      endpoint: "${env:DT_ENDPOINT}"
      headers:
        Authorization: "Api-Token ${env:DT_API_TOKEN}"
    prometheus:
      endpoint: 0.0.0.0:8889

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlphttp]
      metrics:
        receivers: [otlp,prometheus]
        processors: [cumulativetodelta]
        exporters: [otlphttp, prometheus]
      logs:
        receivers: [otlp]
        processors: []
        exporters: [otlphttp]