name: "Install MinIO Client"
description: "Installs MinIO Client (mc) on the runner"
author: "Your Name"
branding:
  icon: "cloud"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Install MinIO Client
      shell: bash
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc
        chmod +x /usr/local/bin/mc
        echo "MinIO Client installed successfully"

    - name: Verify Installation
      shell: bash
      run: mc --version
