name: Build Kong Gateway Image

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment (dev, staging, prod)'
        type: string
        default: dev
      kong_version:
        description: 'Kong Gateway version'
        type: string
        default: "3.9.0.1"
      continue_on_scan_failure:
        description: 'Continue on Trivy scan failure'
        default: 'true'
        type: boolean

jobs:
  build-image:
    runs-on: ubuntu-latest

    env:
      ENV_FILE: .github/env/${{ inputs.environment }}.yaml
      DOCKERFILE_DIR: ${{ github.workspace }}/examples/image-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment configuration
        uses: ./.github/actions/load-config
        with:
          environment: ${{ inputs.environment }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to the Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Import CA Certificate
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            pki/cert/ca certificate | CA_CERT ;

      - name: Save CA Certificate to file
        run: |
          echo "${{ steps.import-secrets.outputs.CA_CERT }}" > myCA.crt
        shell: bash
        working-directory: ${{ env.DOCKERFILE_DIR }}

      - name: Fetch Custom Plugin
        run: |
          git clone https://github.com/Kong/kong-plugin.git
        working-directory: ${{ env.DOCKERFILE_DIR }}

      - name: Download Kong Gateway
        run: |
          KONG_VERSION="${{ inputs.kong_version }}"
          KONG_MAJOR_MINOR_VERSION=$(echo "$KONG_VERSION" | cut -d. -f1-2 | tr -d '.')
          KONG_PACKAGE_NAME="kong-enterprise-edition_${KONG_VERSION}_amd64.deb"
          KONG_URL="https://packages.konghq.com/public/gateway-${KONG_MAJOR_MINOR_VERSION}/deb/debian/pool/bullseye/main/k/ko/kong-enterprise-edition_${KONG_VERSION}/${KONG_PACKAGE_NAME}"

          echo "Downloading Kong Gateway version: $KONG_VERSION (major version: $KONG_MAJOR_MINOR_VERSION)..."
          echo "Fetching from URL: $KONG_URL"

          curl -s -o kong.deb "$KONG_URL"
        working-directory: ${{ env.DOCKERFILE_DIR }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          platforms: linux/amd64
          push: false
          load: true
          tags: ${{ env.DOCKER_IMAGE_REPO }}:${{ env.KONG_VERSION }}

      - name: Scan Docker image with Trivy (Table Format)
        continue-on-error: ${{ inputs.continue_on_scan_failure }}
        run: |
          trivy image --exit-code 1 --no-progress ${{ env.DOCKER_IMAGE_REPO }}:${{ env.KONG_VERSION }}

      - name: Save Trivy Scan Results (JSON Format)
        continue-on-error: ${{ inputs.continue_on_scan_failure }}
        run: |
          mkdir -p reports
          trivy image --format json --output reports/trivy-report.json ${{ env.DOCKER_IMAGE_REPO }}:${{ env.KONG_VERSION }}

      - name: Create docker network for smoke tests
        run: |
          docker network create kong-net-${{ github.run_id }}
        continue-on-error: true

      - name: Run docker container
        run: |
            docker run -d --name kong-gateway \
            --network kong-net-${{ github.run_id }} \
            -p 8000:8000 -p 8100:8100 -p 8443:8443 \
            --env KONG_DATABASE=off \
            --env KONG_PLUGINS=bundled,myplugin \
            --env KONG_STATUS_LISTEN=0.0.0.0:8100 \
            --env KONG_DECLARATIVE_CONFIG=/kong.yaml \
            --env KONG_NGINX_WORKER_PROCESSES=1 \
            --health-cmd "kong health" \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 3 \
            --volume $(pwd)/kong.yaml:/kong.yaml \
            ${{ env.DOCKER_IMAGE_REPO }}:${{ env.KONG_VERSION }}
        working-directory: ${{ env.DOCKERFILE_DIR }}

      - name: Wait for Kong Gateway to start
        run: |
          timeout 60s sh -c 'until docker ps | grep kong-gateway | grep -q healthy; do echo "Waiting for Kong Gateway to be available..."; sleep 2; done'
        shell: bash

      - name: Run smoke tests
        run: |
          bats kong-smoke-tests.bats | tee ${{ github.workspace }}/reports/smoke_test_report.log
        working-directory: ${{ github.workspace }}/scripts

      - name: Run Load tests
        run: |
          set -e
          k6 run --vus 50 --duration 10s -e K6_TEST_URL=http://localhost:8000 examples/image-build/k6/load.js
        working-directory: ${{ github.workspace }}

      - name: Stop and remove Docker container and network
        if: always()
        run: |
          docker stop kong-gateway
          docker rm kong-gateway
          docker network rm kong-net-${{ github.run_id }}

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.KONG_VERSION }}

      - name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_REPO }}:${{ env.KONG_VERSION }}

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/*