name: Build Kong Gateway Image

on:
  workflow_call:
    inputs:
      kong_image_repo:
        description: 'Kong Gateway image repository'
        required: true
        type: string
      kong_image_tag:
        description: 'Kong Gateway image tag'
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download docker-entrypoint.sh
        run: |
          curl -s -o docker-entrypoint.sh https://raw.githubusercontent.com/Kong/docker-kong/master/docker-entrypoint.sh
          chmod +x docker-entrypoint.sh
        working-directory: docker

      - name: Download Kong Gateway RPM
        run: |
          curl -s -o kong.rpm https://packages.konghq.com/public/gateway-37/rpm/el/8/x86_64/kong-enterprise-edition-3.7.0.0.el8.x86_64.rpm
        working-directory: docker

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/amd64
          push: false
          tags: ${{ inputs.kong_image_repo }}:${{ inputs.kong_image_tag }}

      - name: Run docker container
        run: |
          docker run -d --name kong-gateway \
            -p 8000:8000 -p 8100:8100 \
            --env KONG_DATABASE=off \
            --env KONG_STATUS_LISTEN=0.0.0.0:8100 \
            --env KONG_DECLARATIVE_CONFIG=/kong.yaml \
            --health-cmd "kong health" \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 3 \
            --volume $(pwd)/kong.yaml:/kong.yaml \
            ${{ inputs.kong_image_repo }}:${{ inputs.kong_image_tag }}
          echo "Waiting 15s for Kong to start..."
          sleep 15
        shell: bash
        working-directory: docker

      - name: Test Kong Gateway Status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8100/status)
          echo "Response code: $response"
        shell: bash
        working-directory: docker

      - name: Test Kong Gateway Proxy
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/something)
          echo "Response code: $response"
        shell: bash
        working-directory: docker

      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop kong-gateway
          docker rm kong-gateway

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: docker
          platforms: linux/amd64
          push: false
          tags: ${{ inputs.kong_image_repo }}:${{ inputs.kong_image_tag }}