name: Deploy Kong Data Plane

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Kubernetes namespace'
        type: string
        default: 'kong-observability'
      control_plane_name:
        description: 'The name of the control plane to configure'
        type: string
        required: true
      konnect_server_url:
        description: 'Konnect server URL'
        type: string
        default: https://eu.api.konghq.com
      action:
        description: 'Action to perform'
        required: true
        type: string
        default: 'deploy' # 'deploy' or 'destroy'

jobs: 
  prepare:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: ${{ inputs.namespace }}
      KUBECONFIG: /.kube/config

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure global observability plugins
        if: ${{ inputs.action == 'deploy' }}
        run: |
          deck gateway sync ${{ github.workspace }}/examples/observability/kong.yaml  \
            --konnect-addr=${{ inputs.konnect_server_url }} \
            --konnect-token=${{ secrets.KONNECT_PAT }} \
            --konnect-control-plane-name=${{ inputs.control_plane_name }}
      
      - name: kubectl use context
        run: |
          kubectl config use-context kind-konnect-platform-ops-demo
          
      - name: Create Kong observability namespace if not exists
        if: ${{ inputs.action == 'deploy' }}
        run: |
          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Required Helm Repositories
        if: ${{ inputs.action == 'deploy' }}
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Deploy Grafana tempo
        run: |
          helm upgrade --install tempo grafana/tempo -n $NAMESPACE --values ${{ github.workspace }}/k8s/tempo/values.yaml

      - name: Create Grafana Kong dashboard ConfigMap
        if: ${{ inputs.action == 'deploy' }}
        run: |
          kubectl -n $NAMESPACE create cm grafana-kong-official --from-file=${{ github.workspace }}/k8s/grafana/dashboards/kong-official.json --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n $NAMESPACE label cm grafana-kong-official grafana_dashboard="1"

      - name: Deploy Prometheus Stack
        if: ${{ inputs.action == 'deploy' }}
        run: |
          helm upgrade --install kong-prometheus prometheus-community/kube-prometheus-stack -n $NAMESPACE --values ${{ github.workspace }}/k8s/prom/values.yaml
      
      