name: Provision Konnect

on:
  workflow_call:
    inputs:
      namespace:
        description: 'Kubernetes namespace'
        default: 'kong'
        type: string
      konnect_server_url:
        description: 'Kong Konnect Server URL'
        type: string
        default: "https://eu.api.konghq.com"
      vault_addr:
        description: 'Vault Address'
        default: 'http://localhost:8300'
        type: string
      config_file:
        description: 'Path to the configuration file'
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_konnect_personal_access_token: ${{ secrets.KONNECT_PAT }}
      TF_VAR_konnect_server_url:  ${{ inputs.konnect_server_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
      
      - name: Import Certificates
        id: import-certs
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ inputs.vault_addr }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/certificates/demo ca | CA_CRT

      - name: Save CA Certificate to file
        run: |
          mkdir -p .tls
          touch .tls/ca.crt
          echo '${{ steps.import-certs.outputs.CA_CRT }}' >> .tls/ca.crt

      - name: Setup teams to be removed
        run: |
          echo '{
            "teams": [],
            "control_planes": [],
            "system_accounts": [],
            "control_plane_groups": []
          }' | jq '.' > ../../terraform/resources.json
        working-directory: scripts/teams

      - name: Terraform Init
        run: |
          terraform init -backend-config=config.s3.tfbackend \
            -backend-config="bucket=tfstate" \
            -backend-config="key=konnect.tfstate" \
            -backend-config="region=main" \
            -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}"
        working-directory: terraform

      - name: Terraform destroy
        run: |
          terraform destroy -auto-approve
        working-directory: terraform

      - name: Remove teams
        id: remove-teams
        run: |
          pip install -r requirements.txt
          python3 main.py --config-file=../../${{ inputs.config_file }} --wipe=true
        working-directory: scripts/teams
        env:
          KONNECT_ACCESS_TOKEN: ${{ secrets.KONNECT_PAT }}
          KONNECT_ADDRESS: https://global.api.konghq.com

      - name: Remove Dataplane namespace
        run: |
          kubectl delete namespace ${{ inputs.namespace }}
