name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      action: # Can be either 'provision' or 'destroy'
        description: 'Action to perform'
        required: true
        type: string
        default: 'provision'
      config_file:
        description: 'Path to the configuration file'
        required: true
        type: string

env:
  KONNECT_SERVER_URL: "https://eu.api.konghq.com"
  KONG_IMAGE_REPO: "kong/kong-gateway"
  KONG_IMAGE_TAG: "3.7.0.0"
  KONG_K8S_NAMESPACE: "kong"

jobs:
  provision-konnect:
    if: ${{ github.event.inputs.action == 'provision' }}
    uses: ./.github/workflows/reusable-workflows/provision-konnect.yaml
    with:
      konnect_pat: ${{ secrets.KONNECT_PAT }}
      konnect_server_url: ${{ env.KONNECT_SERVER_URL }}
      s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
      config_file: ${{ github.event.inputs.config_file }}

  deploy-cp:
    if: ${{ github.event.inputs.action == 'provision' }}
    uses: ./.github/workflows/reusable-workflows/deploy-dp.yaml
    needs: provision-konnect
    with:
      namespace: ${{ env.KONG_K8S_NAMESPACE }}
      kong_image_repo: ${{ env.KONG_IMAGE_REPO }}
      kong_image_tag: ${{ env.KONG_IMAGE_TAG }}
      tf_output: ${{ needs.provision-konnect.outputs.tf_output }}

  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    uses: ./.github/workflows/reusable-workflows/destroy.yaml
    with:
      namespace: ${{ env.KONG_K8S_NAMESPACE }}
      konnect_pat: ${{ secrets.KONNECT_PAT }}
      konnect_server_url: ${{ env.KONNECT_SERVER_URL }}
      s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.S3_SECRET_KEY }}
      config_file: ${{ github.event.inputs.config_file }}