name: Publish API

on:
  workflow_call:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        type: string
      konnect_server_url:
        description: "Kong Konnect server url"
        type: string
        default: "https://eu.api.konghq.com"
      control_plane_name:
        description: "Kong Konnect control plane name"
        type: string
        required: true
      vault_addr:
        description: 'Vault Address'
        default: 'http://192.168.178.42:8300'
        type: string
      system_account:
        description: 'The system account to use for authentication'
        type: string
        required: true

env:
  DECK_API_NAME: petstore # To be used as a tag
  DECK_CONFIG_OWNER: team1 # To be used as a tag
  DECK_CONFIG_OIDC_ISSUER: ${{ secrets.OIDC_ISSUER }}

jobs:
  publish-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import system account Token
        id: import-token
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ inputs.vault_addr }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/system-accounts/${{ inputs.system_account }} token | system_account_TOKEN ;

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y_%m_%dT%H_%M_%S')" >> $GITHUB_ENV

      - name: Patch Open API Specification
        run: |
          yq eval-all -P 'select(fileIndex == 0) * select(fileIndex == 1)' ${{ github.workspace }}/${{ inputs.openapi_spec }} patches/oas.yaml > oas-patched.yaml
          cat oas-patched.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Lint OpenAPI Specification
        run: |
          spectral lint oas-patched.yaml --ruleset .spectral.yaml -o oas_lint_results_${{ env.NOW }}.txt
          # inso lint spec ${{ github.workspace }}/examples/apiops/oas-patched.yaml --workingDir ${{ github.workspace }}/examples/apiops
          cat oas_lint_results_${{ env.NOW }}.txt
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: DeckOps
        run: |

          # Convert OpenAPI Specification to Kong Gateway configuration
          cat oas-patched.yaml | deck file openapi2kong > kong.yaml

          # Merge Kong Gateway configuration files -  Add consumers
          deck file merge -o kong.yaml kong.yaml additions/consumers.yaml

          # Add plugins to the Kong Gateway configuration
          cat kong.yaml | deck file add-plugins \
            plugins/openid-connect.yaml \
            plugins/request-termination.yaml \
            plugins/rate-limiting.yaml -o kong.yaml

          # Add namespace to the Kong Gateway routes
          cat kong.yaml | deck file namespace --path-prefix=/${{ env.DECK_API_NAME }} -o kong.yaml

          # Patch the Kong Gateway configuration
          cat kong.yaml | deck file patch patches/patches.yaml -o kong.yaml

          # Print the resulting Kong Gateway configuration
          cat kong.yaml

        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Validate Generated Kong Gateway configuration
        run: |
          deck file validate kong.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Get a backup of the current Kong Gateway configuration
        run: |
          deck gateway dump \
            --konnect-addr=${{ inputs.konnect_server_url }} \
            --konnect-token=${{ steps.import-token.outputs.system_account_TOKEN }} \
            --konnect-control-plane-name=${{ inputs.control_plane_name }} -o kong_backup_${{ env.NOW }}.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Diff Kong Gateway configuration
        run: |
          deck gateway diff kong.yaml  \
            --konnect-addr=${{ inputs.konnect_server_url }} \
            --konnect-token=${{ steps.import-token.outputs.system_account_TOKEN }} \
            --konnect-control-plane-name=${{ inputs.control_plane_name }} > diff_${{ env.NOW }}.txt
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/examples/apiops/kong_backup_${{ env.NOW }}.yaml
            ${{ github.workspace }}/examples/apiops/diff_${{ env.NOW }}.txt
            ${{ github.workspace }}/examples/apiops/oas_lint_results_${{ env.NOW }}.txt

      - name: Sync Kong Gateway configuration
        run: |
          deck gateway sync kong.yaml  \
            --konnect-addr=${{ inputs.konnect_server_url }} \
            --konnect-token=${{ steps.import-token.outputs.system_account_TOKEN }} \
            --konnect-control-plane-name=${{ inputs.control_plane_name }}
        working-directory: ${{ github.workspace }}/examples/apiops

