name: Publish API

on:
  workflow_call:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        required: true
        type: string
      konnect_server_url:
        description: "Kong Konnect server url"
        type: string
        default: "https://eu.api.konghq.com"
      control_plane_name:
        description: "Kong Konnect control plane name"
        type: string
        required: true
      vault_addr:
        description: 'Vault Address'
        default: 'http://localhost:8300'
        type: string
      system_account:
        description: 'The system account to use for authentication'
        type: string
        required: true
      api_url:
        description: 'API URL'
        type: string
        required: false
      api_name:
        description: 'API Name'
        type: string
        required: false
        default: 'petstore'

env:
  DECK_API_NAME: ${{ inputs.api_name }} # To be used as a tag
  DECK_CONFIG_OWNER: team1 # To be used as a tag
  DECK_CONFIG_OIDC_ISSUER: ${{ secrets.OIDC_ISSUER }}
  DECK_API_URL: ${{ inputs.api_url }}

jobs:
  publish-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install extra rulesets for Spectral
        run: |
          npm install --save -D @stoplight/spectral-owasp-ruleset@^2.0

      - name: Import system account Token
        id: import-token
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ inputs.vault_addr }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/system-accounts/${{ inputs.system_account }} token | system_account_TOKEN ;

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y_%m_%dT%H_%M_%S')" >> $GITHUB_ENV

      - name: Patch Open API Specification
        run: |

          # Merge the OpenAPI Specification with the patches
          yq eval-all -P 'select(fileIndex == 0) * select(fileIndex == 1)' ${{ github.workspace }}/${{ inputs.openapi_spec }} patches/oas.yaml > oas-patched.yaml
          
          # Remove servers with x-internal: false
          yq e -i 'del(.servers[] | select(.x-internal == false))' oas-patched.yaml

        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Lint OpenAPI Specification
        run: |
          spectral lint oas-patched.yaml --ruleset .spectral.yaml -o oas_lint_results_${{ env.NOW }}.txt
          # inso lint spec ${{ github.workspace }}/examples/apiops/oas-patched.yaml --workingDir ${{ github.workspace }}/examples/apiops
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Show linting results
        if: always()
        run: cat oas_lint_results_${{ env.NOW }}.txt
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: DeckOps
        run: |

          # Convert OpenAPI Specification to Kong Gateway configuration
          cat oas-patched.yaml | deck file openapi2kong > kong.yaml

          # Merge Kong Gateway configuration files -  Add consumers
          deck file merge -o kong.yaml kong.yaml additions/consumers.yaml

          # Add plugins to the Kong Gateway configuration
          cat kong.yaml | deck file add-plugins \
            plugins/openid-connect.yaml \
            plugins/rate-limiting.yaml -o kong.yaml

          # Add namespace to the Kong Gateway routes
          cat kong.yaml | deck file namespace --path-prefix=/${{ env.DECK_API_NAME }} -o kong.yaml

          # Patch the Kong Gateway configuration
          cat kong.yaml | deck file patch patches/select_tags.yaml -o kong.yaml

          # Patch the service URL only if DECK_API_URL is set
          if [ -n "${{ env.DECK_API_URL }}" ]; then
            cat kong.yaml | deck file patch patches/service.yaml -o kong.yaml
          fi

          # Print the resulting Kong Gateway configuration
          cat kong.yaml

        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Validate Generated Kong Gateway configuration
        run: |
          deck file validate kong.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Get a backup of the previous Kong Gateway configuration
        run: |
          deck gateway dump \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" -o kong_backup_${{ env.NOW }}.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Diff Kong Gateway configuration
        run: |
          deck gateway diff kong.yaml  \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" > diff_${{ env.NOW }}.txt
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Sync Kong Gateway configuration
        run: |
          deck gateway sync kong.yaml  \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}"
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Get a backup of the current Kong Gateway configuration
        run: |
          deck gateway dump \
            --konnect-addr="${{ inputs.konnect_server_url }}" \
            --konnect-token="${{ steps.import-token.outputs.system_account_TOKEN }}" \
            --konnect-control-plane-name="${{ inputs.control_plane_name }}" -o kong_current_${{ env.NOW }}.yaml
        working-directory: ${{ github.workspace }}/examples/apiops

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/examples/apiops/kong_backup_${{ env.NOW }}.yaml
            ${{ github.workspace }}/examples/apiops/kong_current_${{ env.NOW }}.yaml
            ${{ github.workspace }}/examples/apiops/diff_${{ env.NOW }}.txt
            ${{ github.workspace }}/examples/apiops/oas_lint_results_${{ env.NOW }}.txt

