name: Provision Konnect

on:
  workflow_call:
    inputs:
      config_file:
        description: 'Path to the configuration file'
        type: string
      vault_addr:
        description: 'Vault Address'
        type: string
        default: 'http://localhost:8300'
      action:
        description: 'Action to perform'
        required: true
        type: string
        default: 'provision' # 'provision' or 'destroy'
      environment:
        description: 'Environment to provision'
        type: string
        default: 'local'

jobs:
  provision-konnect:
    runs-on: ubuntu-latest

    env:
      TF_VAR_konnect_personal_access_token: ${{ secrets.KONNECT_PAT }}
      TF_VAR_environment: ${{ inputs.environment }}
      TERRAFORM_DIR: 'terraform/environments/local/federated'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
      
      - name: Import Certificates
        id: import-certs
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ inputs.vault_addr }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/certificates/demo ca | CA_CRT

      - name: Save CA Certificate to file
        run: |
          mkdir -p .tls
          touch .tls/ca.crt
          echo '${{ steps.import-certs.outputs.CA_CRT }}' >> .tls/ca.crt
        working-directory: ${{ github.workspace }}/${{ env.TERRAFORM_DIR }}

      - name: Provision team
        id: provision-team
        if: ${{ inputs.action == 'provision' }}
        run: |

          team_name=$(jq -r '.metadata.name' ${{ github.workspace }}/${{ inputs.config_file }})
          pip install -r requirements.txt
          output=$(python3 main.py --config-file=${{ github.workspace }}/${{ inputs.config_file }} --extra-labels genplan=federated teamid=$team_name)
          echo "$output" > ${{ github.workspace }}/${{ env.TERRAFORM_DIR }}/resources.json
        working-directory: scripts/teams
        env:
          KONNECT_ACCESS_TOKEN: ${{ secrets.KONNECT_PAT }}
          KONNECT_ADDRESS: https://global.api.konghq.com

      - name: Create MinIO bucket if not exists
        run: |
          
          team_name=$(jq -r '.metadata.name' ${{ github.workspace }}/${{ inputs.config_file }})
          mc alias set $team_name http://localhost:9000 minio-root-user minio-root-password
          ./create-minio-bucket.sh $team_name $team_name.tfstate
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
        working-directory: scripts

      - name: Setup terraform variables
        id: tfvars
        run: |
          
          region=$(cat ${{ github.workspace }}/${{ inputs.config_file }} | jq -r .metadata.region)
          team_name=$(jq -r '.metadata.name' ${{ github.workspace }}/${{ inputs.config_file }})
          
          echo "konnect_server_url=https://$region.api.konghq.com" >> $GITHUB_OUTPUT
          echo "team_name=$team_name" >> $GITHUB_OUTPUT
        working-directory: ${{ github.workspace }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config=config.s3.tfbackend \
            -backend-config="bucket=${{ steps.tfvars.outputs.team_name }}.tfstate" \
            -backend-config="key=konnect.tfstate" \
            -backend-config="region=main" \
            -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}"
        working-directory: ${{env.TERRAFORM_DIR}}
        env:
          TF_VAR_konnect_server_url: ${{ steps.tfvars.outputs.konnect_server_url }}

      - name: Terraform Plan
        if: ${{ inputs.action == 'provision' }}
        run: |
          terraform plan -out=tfplan
        working-directory: ${{env.TERRAFORM_DIR}}
        env:
          TF_VAR_konnect_server_url: ${{ steps.tfvars.outputs.konnect_server_url }}

      - name: Terraform Apply
        if: ${{ inputs.action == 'provision' }}
        id: tfapply
        run: |
          terraform apply -auto-approve tfplan
          echo "$(terraform-bin output -json kong_gateway_control_plane_info | jq '[.[]]')" > kong_gateway_control_plane_info.json
          echo "$(terraform-bin output -json system_account_access_tokens)" > system_account_tokens.json
        working-directory: ${{env.TERRAFORM_DIR}}
        env:
          TF_VAR_konnect_server_url: ${{ steps.tfvars.outputs.konnect_server_url }}

      - name: Store System Account tokens in Vault
        if: ${{ inputs.action == 'provision' }}
        run: |
          for row in $(cat system_account_tokens.json | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }

            secret_name=$(_jq '.name')
            secret_value=$(_jq '.token')

            vault kv put secret/system-accounts/${secret_name} token=${secret_value}

            echo "Stored secret ${secret_name} in Vault."
          done

        working-directory: ${{env.TERRAFORM_DIR}}
        env:
          VAULT_ADDR: ${{ inputs.vault_addr }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

      - name: Setup teams to be removed
        run: |
          echo '{}' | jq '.' > ${{ github.workspace }}/${{ env.TERRAFORM_DIR }}/resources.json
  
      - name: Terraform destroy
        if: ${{ inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve
        working-directory: ${{env.TERRAFORM_DIR}}
        env:
          TF_VAR_konnect_server_url: ${{ steps.tfvars.outputs.konnect_server_url }}

      - name: Remove team
        if: ${{ inputs.action == 'destroy' }}
        run: |
          team_name=$(jq -r '.metadata.name' ${{ github.workspace }}/${{ inputs.config_file }})
          pip install -r requirements.txt
          python3 main.py --config-file=../../${{ inputs.config_file }} --extra-labels genplan=federated teamid=$team_name --wipe=true
        working-directory: scripts/teams
        env:
          KONNECT_ACCESS_TOKEN: ${{ secrets.KONNECT_PAT }}
          KONNECT_ADDRESS: https://global.api.konghq.com
