name: Provision Konnect

on:
  workflow_call:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        required: true
        type: string
      environment:
        description: 'Environment to provision'
        type: string
        default: 'local'
      konnect_region:
        description: 'Konnect region where the API Product will be published'
        type: string
        required: true
        default: 'eu'
      konnect_control_plane_id:
        description: 'Konnect Control Plane ID'
        type: string
        required: true
      konnect_gateway_service_id:
        description: 'Konnect Gateway Service ID'
        type: string
        required: true
      action: 
        description: 'Action to perform'
        type: string
        required: true
        default: 'publish' # Options: publish, destroy
      
jobs:
  provision-konnect:
    runs-on: ubuntu-latest

    env:
      TF_VAR_konnect_personal_access_token: ${{ secrets.KONNECT_PAT }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_konnect_server_url: https://${{ inputs.konnect_region }}.api.konghq.com
      TF_VAR_konnect_control_plane_id: ${{ inputs.konnect_control_plane_id }}
      TF_VAR_konnect_gateway_service_id: ${{ inputs.konnect_gateway_service_id }}
      TERRAFORM_DIR: ${{ github.workspace }}/terraform/environments/${{ inputs.environment }}/api_product

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'

      - name: Setup tfvars
        id: tfvars
        run: |

          # Determine api name, version, description from openapi spec and set as terraform vars
          api_name=$(yq eval '.info.title' ${{ github.workspace }}/${{ inputs.openapi_spec }})
          api_version=$(yq eval '.info.version' ${{ github.workspace }}/${{ inputs.openapi_spec }})
          api_description=$(yq eval '.info.description' ${{ github.workspace }}/${{ inputs.openapi_spec }})
          product_name=$(echo $api_name | tr '[:upper:]' '[:lower:]' | tr ' ' '-')product
          
          echo "TF_VAR_api_name=$api_name" >> $GITHUB_ENV
          echo "TF_VAR_api_version=$api_version" >> $GITHUB_ENV
          echo "TF_VAR_api_description=$api_description" >> $GITHUB_ENV
          echo "TF_VAR_product_name=$product_name" >> $GITHUB_ENV
          
          # Plan ID will be the product name. 
          # We will use this to create a unique S3 bucket for storing tfstate for the specific product.
          echo "::set-output name=planid::$product_name"

      - name: Create S3 bucket if not exists
        run: |
          ./create-minio-bucket.sh ${{ steps.tfvars.outputs.planid }} ${{ steps.tfvars.outputs.planid }}.tfstate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
        working-directory: scripts

      - name: Copy spec to terraform dir
        run: |
          cp ${{ github.workspace }}/${{ inputs.openapi_spec }} ${{env.TERRAFORM_DIR}}/openapi_spec.yaml
        working-directory: ${{env.TERRAFORM_DIR}}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config=config.s3.tfbackend \
            -backend-config="bucket=${{ steps.tfvars.outputs.planid }}.tfstate" \
            -backend-config="key=konnect.tfstate" \
            -backend-config="region=main" \
            -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
            -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}"
        working-directory: ${{env.TERRAFORM_DIR}}

      - name: Terraform Plan
        if: ${{ inputs.action == 'publish' }}
        run: |
          terraform plan -out=tfplan
        working-directory: ${{env.TERRAFORM_DIR}}

      - name: Terraform Apply
        if: ${{ inputs.action == 'publish' }}
        id: tfapply
        run: |
          terraform apply -auto-approve tfplan
          # echo "$(terraform-bin output -json kong_gateway_control_plane_info | jq '[.[]]')" > kong_gateway_control_plane_info.json
          # echo "$(terraform-bin output -json system_account_access_tokens)" > system_account_tokens.json
        working-directory: ${{env.TERRAFORM_DIR}}

      - name: Terraform destroy
        if: ${{ inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve
        working-directory: ${{env.TERRAFORM_DIR}}