name: Provision Konnect Team resources

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/provision-konnect-team-resources.yaml
    with:
      environment: dev
      action: destroy
      config: ./examples/platformops/federated/teams/kronos/resources.json