name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  provision-konnect:
    uses: ./.github/workflows/reusable-workflows/provision-konnect.yaml
    with:
      konnect_pat: ${{ secrets.KONNECT_PAT }}
      konnect_server_url: "https://eu.api.konghq.com"
      s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.S3_SECRET_KEY }}

  deploy-cp:
    uses: ./.github/workflows/reusable-workflows/deploy-dp.yaml
    needs: provision-konnect
    with:
      namespace: kong
      tf_output: ${{ needs.provision-konnect.outputs.tf_output }}
      tls_cert: ${{ needs.provision-konnect.outputs.tls_cert }}
      tls_key: ${{ needs.provision-konnect.outputs.tls_key }}